services:
  - type: web
    name: whosenxt-backend
    env: python
    region: ohio
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
